GET http://localhost:4242/concept/title
Content-Type: application/json

###

POST http://localhost:4242/news
Content-Type: application/json

{
  "Title": "firstName",
  "LastName": "lastName",
  "JobName": "jobName",
  "Photo_id": 1
}

###

PUT http://localhost:4242/slider/title
Content-Type: application/json

{
  "Titre": "Une solution"
}